version: "3.9"

services:
  
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # 콘솔 UI
    environment:
      MINIO_ROOT_USER: chadamjin
      MINIO_ROOT_PASSWORD: chadamjin123   # 운영은 더 강하게!
    command: server /data --console-address ":9001"
    volumes:
      - /mnt/minio/data:/data          # 데이터(여기에 오디오가 저장됨)


  

volumes:
  mongo_data:
