version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


volumes:
  mongo_data:
